build:
  build:
    nodes:
      analysis:
        project_setup:
          override:
            - 'true'
          tests:
            override:
              - php-scrutinizer-run --enable-security-analysis
              - command: phpcs-run
                use_website_config: true

filter:
  excluded_paths:
    - 'tests/*'
    - 'src/Business/Events/*'
